### ISSUE TITLE
Creating an API for getting Exam/s

### ISSUE THREAD

**Issue by avanirpatel6** [micro-exam/micro-exam-exam-api#9]
-A user can view all exams, one exam.
-Get all exams(by classID) /exams/{ClassID}
-Get exam by classID and Exam ID /findExam/{ClassID}/{ExamID}
-Get exam by ExamID /findExamByID/{ExamID}

**Comment by avanirpatel6** [comment]
The exam structure:

| Class ID| ExamID | Q_ID | Q_Text | Q_Type | Answer |
| --- | --- | ----- | ---- | ---- |
| 001 | 111 | 555 | asd | MC | BLOB |
| 001 | 111 | 556 | bdsk | OE | BLOB |

**Comment by s-pat** [comment]
@Neil1213 @avanirpatel6 Can we discuss this ticket. I am blocked by how to face the classid part in the exam's api.
